name: Deploy pages
on:
  workflow_call:
    inputs:
      group:
        description: Group matching the artifacts
        type: string
        default: '*'

jobs:
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
    - name: Merge artifacts by group
      id: merge-artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: ${{ inputs.group }}
        pattern: ${{ format('{0}*', inputs.group) }}
        separate-directories: true
        delete-merged: true

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: ${{ steps.merge-artifacts.outputs.artifact-id }}
        preview: true # TODO: for test

